const runSendNewBetEmail = require('./consumers/send_new_bet_email')
const runSendAdminNewBetEmail = require('./consumers/send_admin_new_bet_email')
const runLetBetUsEmail = require('./consumers/send_let_bet_us_email')
const runResetPasswordEmail = require('./consumers/send_reset_password_email')
const runSendWelcomeEmail = require('./consumers/send_welcome_email')

runSendNewBetEmail().catch(console.error)
runSendAdminNewBetEmail().catch(console.error)
runLetBetUsEmail().catch(console.error)
runResetPasswordEmail().catch(console.error)
runSendWelcomeEmail().catch(console.error)