version: '3'

services:
  db:
    container_name: loteria-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: bet-system

  api:
    build: .
    container_name: loteria-api
    restart: unless-stopped
    volumes:
      - .:/user/app/
    ports:
      - "3333:3333"
    depends_on:
      - db
    command: node ace serve --watch

